
services:
  fastapijenkins:
    image: https://github.com/hocinilotfi/jenkinsfile-postman-fastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8988:8988
    networks:
      - jenkins
networks:
  jenkins:
    driver: bridge